['text':' Owner(s): ["oncall: distributed"]','line_number':1,'multiline':False]
['text':' User doesn't call barrier with tensor.','line_number':36,'multiline':False]
['text':' For CUDA, only assert on device type, not index','line_number':42,'multiline':False]
['text':' C++ and python type strings are not exactly the same.','line_number':52,'multiline':False]
['text':' Ensure sequence number is logged in error','line_number':60,'multiline':False]
['text':' Ensure info about how collectives diff is in the error.','line_number':62,'multiline':False]
['text':' All ranks besides 1 call allreduce and wrapper_pg should detect a hang','line_number':69,'multiline':False]
['text':' and report an issue with rank 1.','line_number':70,'multiline':False]
['text':' Rank 0 reports faulty ranks','line_number':78,'multiline':False]
['text':' Gloo can sometimes throw the following error if a rank exits early','line_number':83,'multiline':False]
['text':' before rank 0 calls into the allreduce.','line_number':84,'multiline':False]
['text':' Run a few successful collectives','line_number':94,'multiline':False]
['text':' Simulate mismatch: allreduce vs reduce.','line_number':102,'multiline':False]
['text':' Error including info about inconsistent collective, rank, tensor','line_number':103,'multiline':False]
['text':' shape, device, and dtype should be raised.','line_number':104,'multiline':False]
['text':' Check errors are raised when dimensionality of shapes is different','line_number':159,'multiline':False]
['text':' Check shape errors with scatter','line_number':172,'multiline':False]
['text':' ASAN is not safe since we are spawning processes.','line_number':203,'multiline':False]
['text':' TORCH_NCCL_BLOCKING_WAIT overrides TORCH_NCCL_ASYNC_ERROR_HANDLING hence tests','line_number':212,'multiline':False]
['text':' that use TORCH_NCCL_BLOCKING_WAIT will test it as expected.','line_number':213,'multiline':False]
['text':' NOTE: these tests are separated by debug level instead of combined into','line_number':254,'multiline':False]
['text':' one due to https://github.com/pytorch/pytorch/issues/55967, they can be','line_number':255,'multiline':False]
['text':' combined after that is resolved.','line_number':256,'multiline':False]
['text':' NOTE: these tests are separated by debug level instead of combined into','line_number':384,'multiline':False]
['text':' one due to https://github.com/pytorch/pytorch/issues/55967, they can be','line_number':385,'multiline':False]
['text':' combined after that is resolved.','line_number':386,'multiline':False]
