['text':' workaround for https://github.com/python/cpython/pull/23326','line_number':2,'multiline':False]
['text':' workaround for Python 2 issue: https://bugs.python.org/issue17120','line_number':5,'multiline':False]
['text':' NOTE: It looks like this affects Python 3 as well.','line_number':6,'multiline':False]
