['text':'*
 * Perform continuous renames on 3 collections per database, with the objective to verify that:
 * - Upon successful renames, no data are lost
 * - Upon unsuccessful renames, no unexpected exception is thrown. Admitted errors:
 * ---- NamespaceNotFound (tried to rename a random non-existing collection)
 * ---- ConflictingOperationInProgress (tried to perform concurrent renames on the same source
 *      collection with different target collections)
 * - The aforementioned acceptable exceptions must be thrown at least once, given the high level of
 * concurrency
 *
 * @tags: [
 *   requires_sharding,
 *   # TODO (SERVER-56879): Support add/remove shards in new DDL paths
 *   does_not_support_add_remove_shards,
 *   # This test just performs rename operations that can't be executed in transactions
 *   does_not_support_transactions,
 *  ]
 ','line_number':1,'multiline':True]['text':'
 * Initialize a collection with expected number of chunks/documents and randomly distribute chunks
 ','line_number':27,'multiline':True]['text':' Disallow balancing 'ns' during $setup so it does not interfere with the splits.','line_number':35,'multiline':False]['text':' When balancer is enabled, move chunks could overlap and fail with','line_number':49,'multiline':False]['text':' ConflictingOperationInProgress','line_number':50,'multiline':False]['text':' Allow balancing 'ns' again.','line_number':59,'multiline':False]['text':'
 * Get a random db/coll name from the test lists.
 *
 * Using the thread id to introduce more randomness: it has been observed that concurrent calls to
 * Random.randInt(array.length) are returning too often the same number to different threads.
 ','line_number':63,'multiline':True]['text':'
 * Keep track of raised exceptions in a collection to be checked during teardown.
 ','line_number':76,'multiline':True]['text':' Initialize databases','line_number':131,'multiline':False]['text':' Initialize one sharded collection per db','line_number':136,'multiline':False]['text':' Ensure that NamespaceNotFound and ConflictingOperationInProgress have been raised at','line_number':143,'multiline':False]['text':' least once: with a high level of concurrency, it's too improbable for such exceptions to','line_number':144,'multiline':False]['text':' never be thrown (in that case, it's very likely that a bug has been introduced).','line_number':145,'multiline':False]['text':' Check that at most one collection per test DB is present and that no data has been lost','line_number':148,'multiline':False]['text':' upon multiple renames.','line_number':149,'multiline':False]