['text':' 2-step function call','line_number':1,'multiline':False]['text':' Arguments are evaluated in left-to-right order.','line_number':43,'multiline':False]['text':' See https://github.com/bazelbuild/starlark/issues/13.','line_number':44,'multiline':False]['text':' getattr','line_number':60,'multiline':False]['text':' Regression test for a type mismatch crash (b/168743413).','line_number':76,'multiline':False]['text':' assert_fails evaluates an expression (passed unevaluated in the form of','line_number':79,'multiline':False]['text':' a lambda) and asserts that evaluation fails with the given error.','line_number':80,'multiline':False]['text':' Test of nested def statements.','line_number':84,'multiline':False]['text':' no free vars','line_number':86,'multiline':False]['text':' freevars={x, add}','line_number':87,'multiline':False]['text':' Same, with lambda','line_number':99,'multiline':False]['text':' Test of stateful function values.','line_number':107,'multiline':False]['text':' different seed','line_number':122,'multiline':False]['text':' Attempt to mutate frozen closure state.','line_number':126,'multiline':False]['text':' recursion is disallowed','line_number':131,'multiline':False]['text':' The recursion check breaks function encapsulation:','line_number':138,'multiline':False]['text':' A function g that internally uses a higher-order helper function','line_number':139,'multiline':False]['text':' such as 'call' (or Python's map and reduce) cannot itself be','line_number':140,'multiline':False]['text':' called from within an active call of that helper.','line_number':141,'multiline':False]['text':' The recursion check is based on the syntactic equality','line_number':147,'multiline':False]['text':' (same def statement), not function value equivalence.','line_number':148,'multiline':False]['text':' fn1 and fn2 are both created by the same lambda,','line_number':154,'multiline':False]['text':' but they are distinct and close over different values...','line_number':155,'multiline':False]['text':' ...yet both cannot be called in the same thread:','line_number':162,'multiline':False]['text':' This rule prevents users from writing the Y combinator,','line_number':165,'multiline':False]['text':' which creates a new closure at each step of the recursion.','line_number':166,'multiline':False]['text':' Trivial test of lambda.','line_number':173,'multiline':False]['text':' builder returns a string builder:','line_number':184,'multiline':False]['text':' an opaque, stateful value with methods and open recursion.','line_number':185,'multiline':False]