['text':' Owner(s): ["module: dynamo"]','line_number':1,'multiline':False]
['text':' (reason="pytorch seems to handle refcounts differently")','line_number':40,'multiline':False]
['text':' (reason="pytorch does not raise")','line_number':49,'multiline':False]
['text':' (reason="pytorch seems to handle refcounts differently")','line_number':57,'multiline':False]
