['text':'*
 * Tests that we can resume cloning a collection when a network error occurs in the middle
 * of that process. This also tests that we correctly clean up old cursors on the sync source.
 * Scenarios included:
 *  - failure in first batch
 *  - failure in subsequent batches
 *  - multiple resumable failures during the same clone
 ','line_number':1,'multiline':True]
['text':' Verify the 'find' command received by the primary includes a resume token request.','line_number':11,'multiline':False]
